language: node_js
node_js:
  - '10.17'
install:
  - npm install
script:
  - npm run test:ci
  - npm run build
  - npm run e2e:ci
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then sh scripts/verifyChangelog.sh; fi'
