

export type EventType = 'V1.REQUIRE_CONTEXT' | 'V1.CLOSE' | 'V1.REQUIRE_PERMISSIONS' | string;

export const SHELL_EVENTS = {
  Version1: {
    REQUIRE_CONTEXT: 'V1.REQUIRE_CONTEXT',
    CLOSE: 'V1.CLOSE',
    REQUIRE_PERMISSIONS: 'V1.REQUIRE_PERMISSIONS'
  },
  ERROR: 'ERROR'
};
