
export type ActionType =
'V1.GET_STORAGE_ITEM' |
'V1.SET_STORAGE_ITEM' |
'V1.GET_PERMISSIONS' |
'V1.GET_SETTINGS';

export const SHELL_ACTIONS = {
Version1: {
  GET_STORAGE_ITEM: 'V1.GET_STORAGE_ITEM',
  SET_STORAGE_ITEM: 'V1.SET_STORAGE_ITEM',
  GET_PERMISSIONS: 'V1.GET_PERMISSIONS',
  GET_SETTINGS: 'V1.GET_SETTINGS'
},
ERROR: 'ERROR'
};
