name: fsm-shell push
run-name: '[ON_PUSH fsm-shell] ${{ github.sha }}'

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm i
      - name: Unit tests
        run: npm run test:ci:headless

  publish:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm i
      - name: Run build
        run: npm run build
      - name: Prepare files
        run: |
          mkdir npm_public
          mv release package.json package-lock.json LICENSE npm_public
          cd npm_public
          echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc
      - name: Publish
        run: |
          cd npm_public
          npm publish
