name: fsm-shell pull request
run-name: '[ON_PR fsm-shell] ${{ github.sha }}'

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, labeled, unlabeled]


jobs:
  ensure-mandatory-files:
    runs-on: ubuntu-latest
    continue-on-error: true # Some changes are only relevant for the documentation page
    steps:
      - name: Skip if label 'skip-ensure-mandatory-files' is present
        if: contains(github.event.pull_request.labels.*.name, 'skip-ensure-mandatory-files')
        run: |
          echo "Label 'skip-ensure-mandatory-files' detected, skipping check."
          exit 0
      - uses: actions/checkout@v4
        if: "!contains(github.event.pull_request.labels.*.name, 'skip-ensure-mandatory-files')"
      - name: Check
        if: "!contains(github.event.pull_request.labels.*.name, 'skip-ensure-mandatory-files')"
        env:
          REQUIRED_FILES: CHANGELOG.md package.json package-lock.json
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          FILES_CHANGED=$(git diff --diff-filter='AMTCR' --name-only origin/master HEAD | tr '[:upper:]' '[:lower:]')
          echo $FILES_CHANGED
          array=( $REQUIRED_FILES )
          missing_files=""
          for i in "${array[@]}"
          do
            i_lower=$(echo "$i" | tr '[:upper:]' '[:lower:]')
            [[ ${FILES_CHANGED[*]} =~ $i_lower ]] && echo "$i file found in the changeset" || missing_files="$missing_files $i"
          done
          echo ""
          [ -z "$missing_files" ] && echo "All mandatory files have been modified" || echo "Following files $missing_files have not been modified"
          [ -z "$missing_files" ] && exit 0 || exit 1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm i
      - name: Unit tests
        run: npm run test:ci:headless

  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm i
      - name: Run build
        run: npm run build
